############# English navigation ##############

# main menu
[[main]]
name = "HOME"
url = ""
weight = 1

[[main]]
name = "UBUNTU"
url = "about/"
weight = 2

[[main]]
name = "FEDORA"
url = "contact/"
weight = 3

[[main]]
name = "Pages"
url = "#"
weight = 3
hasChildren = true

  [[main]]
  parent = "Pages"
  name = "Tags"
  url = "tags/"
  weight = 1

  [[main]]
  parent = "Pages"
  name = "Categories"
  url = "categories/"
  weight = 2

# footer menu
[[footer]]
name = "OPENSUSE"
url = "/"
weight = 1

[[footer]]
name = "About"
url = "about/"
weight = 2

[[footer]]
name = "Contact"
url = "contact/"
weight = 3

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 4
